[build]
builder = "nixpacks"
buildCommand = "go build -o wechat-server cmd/wechat-server/main.go "

[deploy]
startCommand = "./wechat-server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"