// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/francisar/chatgpt/v1/demo.proto

// 根据具体的微服务名称做更改

package francisar_chatgpt_v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	api "github.com/grpc-kit/pkg/api"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DemoRequest struct {
	// UUID 资源编号
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Ping 资源内容
	Ping *api.ExampleRequest `protobuf:"bytes,2,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (m *DemoRequest) Reset()         { *m = DemoRequest{} }
func (m *DemoRequest) String() string { return proto.CompactTextString(m) }
func (*DemoRequest) ProtoMessage()    {}
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5a0793eea71c17, []int{0}
}
func (m *DemoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DemoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DemoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DemoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoRequest.Merge(m, src)
}
func (m *DemoRequest) XXX_Size() int {
	return m.Size()
}
func (m *DemoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DemoRequest proto.InternalMessageInfo

func (m *DemoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DemoRequest) GetPing() *api.ExampleRequest {
	if m != nil {
		return m.Ping
	}
	return nil
}

type DemoResponse struct {
	// Pong 返回创建的资源
	Pong *DemoResponse_Pong `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	// Content 多个资源响应内容（无分页属性）
	Content []*api.ExampleResponse `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	// Ping 返回更新的资源
	Ping *api.ExampleResponse `protobuf:"bytes,3,opt,name=ping,proto3" json:"ping,omitempty"`
	// Empty 返回空的内容
	Empty *types.Empty `protobuf:"bytes,4,opt,name=empty,proto3" json:"empty,omitempty"`
}

func (m *DemoResponse) Reset()         { *m = DemoResponse{} }
func (m *DemoResponse) String() string { return proto.CompactTextString(m) }
func (*DemoResponse) ProtoMessage()    {}
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5a0793eea71c17, []int{1}
}
func (m *DemoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DemoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DemoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DemoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResponse.Merge(m, src)
}
func (m *DemoResponse) XXX_Size() int {
	return m.Size()
}
func (m *DemoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResponse proto.InternalMessageInfo

func (m *DemoResponse) GetPong() *DemoResponse_Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *DemoResponse) GetContent() []*api.ExampleResponse {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *DemoResponse) GetPing() *api.ExampleResponse {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *DemoResponse) GetEmpty() *types.Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

type DemoResponse_Pong struct {
	// UUID 资源编号
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Pong 单个资源响应内容
	Pong *api.ExampleResponse `protobuf:"bytes,2,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (m *DemoResponse_Pong) Reset()         { *m = DemoResponse_Pong{} }
func (m *DemoResponse_Pong) String() string { return proto.CompactTextString(m) }
func (*DemoResponse_Pong) ProtoMessage()    {}
func (*DemoResponse_Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5a0793eea71c17, []int{1, 0}
}
func (m *DemoResponse_Pong) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DemoResponse_Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DemoResponse_Pong.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DemoResponse_Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResponse_Pong.Merge(m, src)
}
func (m *DemoResponse_Pong) XXX_Size() int {
	return m.Size()
}
func (m *DemoResponse_Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResponse_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResponse_Pong proto.InternalMessageInfo

func (m *DemoResponse_Pong) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DemoResponse_Pong) GetPong() *api.ExampleResponse {
	if m != nil {
		return m.Pong
	}
	return nil
}

func init() {
	proto.RegisterType((*DemoRequest)(nil), "francisar.chatgpt.v1.DemoRequest")
	golang_proto.RegisterType((*DemoRequest)(nil), "francisar.chatgpt.v1.DemoRequest")
	proto.RegisterType((*DemoResponse)(nil), "francisar.chatgpt.v1.DemoResponse")
	golang_proto.RegisterType((*DemoResponse)(nil), "francisar.chatgpt.v1.DemoResponse")
	proto.RegisterType((*DemoResponse_Pong)(nil), "francisar.chatgpt.v1.DemoResponse.Pong")
	golang_proto.RegisterType((*DemoResponse_Pong)(nil), "francisar.chatgpt.v1.DemoResponse.Pong")
}

func init() {
	proto.RegisterFile("api/francisar/chatgpt/v1/demo.proto", fileDescriptor_ab5a0793eea71c17)
}
func init() {
	golang_proto.RegisterFile("api/francisar/chatgpt/v1/demo.proto", fileDescriptor_ab5a0793eea71c17)
}

var fileDescriptor_ab5a0793eea71c17 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0xb7, 0xb0, 0x6a, 0xec, 0x7a, 0x6a, 0x8c, 0xd9, 0x60, 0x52, 0xeb, 0xf8, 0x6b, 0x63,
	0xe8, 0xd4, 0xad, 0x80, 0x6c, 0xbd, 0x88, 0x91, 0x3b, 0xa9, 0xd1, 0xfb, 0xb4, 0x3b, 0x3b, 0x34,
	0xd0, 0x99, 0xba, 0x9d, 0x5d, 0x44, 0xc2, 0x85, 0x80, 0x37, 0xc5, 0xf0, 0xc3, 0x03, 0x57, 0x63,
	0xb2, 0x27, 0xd1, 0x70, 0x20, 0x98, 0x10, 0x3d, 0x6e, 0xe2, 0x85, 0xa3, 0x47, 0xdd, 0xd2, 0x5d,
	0xff, 0x0c, 0xd3, 0x69, 0x57, 0x88, 0x21, 0xfe, 0xb8, 0xbd, 0x97, 0xf9, 0x7e, 0xbe, 0xef, 0xbd,
	0x79, 0x4f, 0xbe, 0x82, 0x02, 0xcf, 0xa8, 0xd5, 0x11, 0x75, 0xbd, 0x10, 0xd5, 0x0d, 0x77, 0x1a,
	0x71, 0x12, 0x70, 0xa3, 0x59, 0x36, 0xaa, 0xd8, 0x67, 0x30, 0xa8, 0x33, 0xce, 0x94, 0xf3, 0xbf,
	0x04, 0x30, 0x13, 0xc0, 0x66, 0x79, 0xe8, 0x22, 0x61, 0x8c, 0xcc, 0x62, 0x43, 0x68, 0x9c, 0x46,
	0xcd, 0xc0, 0x7e, 0xc0, 0xe7, 0x53, 0x64, 0x48, 0x27, 0x1e, 0x9f, 0x6e, 0x38, 0xd0, 0x65, 0xbe,
	0x41, 0x18, 0x61, 0x47, 0xaa, 0x24, 0x13, 0x89, 0x88, 0x32, 0xf9, 0xc3, 0xe3, 0xf2, 0x7a, 0xe0,
	0xea, 0xd8, 0x65, 0xe1, 0x7c, 0xc8, 0x71, 0x96, 0x12, 0xc4, 0xf1, 0x1c, 0x9a, 0x4f, 0x5d, 0x5c,
	0x9d, 0x60, 0xaa, 0x87, 0x73, 0x88, 0x10, 0x5c, 0x37, 0x58, 0xc0, 0x3d, 0x46, 0x43, 0x03, 0x51,
	0xca, 0x38, 0x12, 0x71, 0x66, 0x0a, 0x7f, 0x37, 0x9d, 0xf1, 0xb8, 0x91, 0xcc, 0x9b, 0x96, 0x6f,
	0x96, 0x0d, 0xfc, 0x14, 0xf9, 0xc1, 0x2c, 0x4e, 0xf5, 0x60, 0x47, 0x92, 0x0b, 0x0f, 0xb0, 0xcf,
	0x6c, 0xfc, 0xa4, 0x81, 0x43, 0xae, 0x28, 0x72, 0xbe, 0xd1, 0xf0, 0xaa, 0x45, 0x49, 0x93, 0x4a,
	0x67, 0x6d, 0x11, 0x2b, 0x15, 0x39, 0x1f, 0x78, 0x94, 0x14, 0x07, 0x34, 0xa9, 0x54, 0x30, 0xaf,
	0xc1, 0xc4, 0x17, 0xce, 0x78, 0x1c, 0xa2, 0xc0, 0x4b, 0x6d, 0x60, 0xb3, 0x0c, 0x27, 0x53, 0xdf,
	0xcc, 0xc8, 0x16, 0x88, 0xf5, 0x68, 0x6d, 0xc2, 0x96, 0x6f, 0x9a, 0xa5, 0xa4, 0x44, 0xf7, 0xf5,
	0x5e, 0x77, 0x67, 0xf3, 0xc7, 0xf6, 0x6e, 0xf7, 0xc3, 0x52, 0xbc, 0xba, 0x7d, 0xb8, 0xff, 0xa9,
	0xb7, 0xd1, 0xea, 0x6d, 0x2d, 0x77, 0x5f, 0xbe, 0x8d, 0x57, 0xdf, 0xc4, 0xab, 0x4b, 0xdd, 0xcd,
	0xf7, 0xe6, 0x55, 0x05, 0x2c, 0x68, 0x20, 0x61, 0x81, 0xa5, 0x2d, 0x68, 0x80, 0x22, 0x1f, 0x03,
	0x4b, 0x03, 0xfd, 0x59, 0x80, 0xb6, 0xa8, 0x2d, 0x82, 0x2f, 0x83, 0xf2, 0xb9, 0xb4, 0xeb, 0x30,
	0x60, 0x34, 0xc4, 0xca, 0x5d, 0x39, 0x1f, 0x30, 0x4a, 0x44, 0xdb, 0x05, 0xf3, 0x06, 0x3c, 0x69,
	0x79, 0xf0, 0x38, 0x01, 0xa7, 0x18, 0x25, 0xb6, 0x80, 0x94, 0x7b, 0xf2, 0x19, 0x97, 0x51, 0x8e,
	0x29, 0x2f, 0x0e, 0x68, 0x83, 0xa5, 0x82, 0x79, 0xfd, 0x6f, 0x23, 0xa6, 0x1e, 0x76, 0x1f, 0x53,
	0xac, 0xec, 0x87, 0x06, 0x45, 0xf9, 0x7f, 0xc5, 0x05, 0xa3, 0x0c, 0xcb, 0xa7, 0xc4, 0x11, 0x15,
	0xf3, 0x02, 0xbe, 0x00, 0xd3, 0x13, 0x83, 0xfd, 0xe3, 0x81, 0x93, 0xc9, 0xab, 0x9d, 0x8a, 0x86,
	0x1e, 0xcb, 0xf9, 0xa4, 0xf3, 0x13, 0xf7, 0x64, 0x65, 0x9f, 0x30, 0xf0, 0x9f, 0x5d, 0x30, 0x4a,
	0xac, 0x67, 0x6b, 0x13, 0x73, 0xf2, 0x65, 0xf3, 0xd2, 0xd1, 0xa2, 0xe2, 0xf5, 0x17, 0xf1, 0xc7,
	0x8d, 0xde, 0xd6, 0x72, 0xbc, 0xb2, 0x7b, 0xb8, 0xbf, 0x1e, 0x3f, 0x5f, 0x89, 0xdf, 0xed, 0x99,
	0xb6, 0x32, 0xb5, 0x00, 0x92, 0x6a, 0xc0, 0x02, 0x95, 0x4a, 0x0d, 0xa3, 0x9a, 0x33, 0xaa, 0x3b,
	0xb8, 0x3a, 0xa6, 0x8f, 0x54, 0x51, 0x4d, 0xaf, 0x98, 0x77, 0x90, 0x3e, 0x56, 0x41, 0x26, 0x72,
	0xc6, 0x6f, 0xb9, 0x23, 0xe3, 0xa3, 0x60, 0x58, 0x03, 0x49, 0x81, 0x3f, 0x6c, 0xf3, 0xfe, 0x70,
	0xfb, 0xbb, 0x2a, 0xb5, 0x3a, 0xaa, 0xd4, 0xee, 0xa8, 0xd2, 0x41, 0x47, 0x95, 0xbe, 0x75, 0x54,
	0xe9, 0x55, 0xa4, 0xe6, 0x5a, 0x91, 0x2a, 0x7d, 0x8e, 0x54, 0xa9, 0x1d, 0xa9, 0xb9, 0x83, 0x48,
	0xcd, 0x7d, 0x8d, 0xd4, 0x9c, 0x73, 0x5a, 0x4c, 0x72, 0xfb, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x33, 0x77, 0x2e, 0x47, 0xc6, 0x03, 0x00, 0x00,
}

func (this *DemoRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*DemoRequest)
	if !ok {
		that2, ok := that.(DemoRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Uuid != that1.Uuid {
		if this.Uuid < that1.Uuid {
			return -1
		}
		return 1
	}
	if c := this.Ping.Compare(that1.Ping); c != 0 {
		return c
	}
	return 0
}
func (this *DemoResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*DemoResponse)
	if !ok {
		that2, ok := that.(DemoResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := this.Pong.Compare(that1.Pong); c != 0 {
		return c
	}
	if len(this.Content) != len(that1.Content) {
		if len(this.Content) < len(that1.Content) {
			return -1
		}
		return 1
	}
	for i := range this.Content {
		if c := this.Content[i].Compare(that1.Content[i]); c != 0 {
			return c
		}
	}
	if c := this.Ping.Compare(that1.Ping); c != 0 {
		return c
	}
	if c := this.Empty.Compare(that1.Empty); c != 0 {
		return c
	}
	return 0
}
func (this *DemoResponse_Pong) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*DemoResponse_Pong)
	if !ok {
		that2, ok := that.(DemoResponse_Pong)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Uuid != that1.Uuid {
		if this.Uuid < that1.Uuid {
			return -1
		}
		return 1
	}
	if c := this.Pong.Compare(that1.Pong); c != 0 {
		return c
	}
	return 0
}
func (this *DemoRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DemoRequest)
	if !ok {
		that2, ok := that.(DemoRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if !this.Ping.Equal(that1.Ping) {
		return false
	}
	return true
}
func (this *DemoResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DemoResponse)
	if !ok {
		that2, ok := that.(DemoResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Pong.Equal(that1.Pong) {
		return false
	}
	if len(this.Content) != len(that1.Content) {
		return false
	}
	for i := range this.Content {
		if !this.Content[i].Equal(that1.Content[i]) {
			return false
		}
	}
	if !this.Ping.Equal(that1.Ping) {
		return false
	}
	if !this.Empty.Equal(that1.Empty) {
		return false
	}
	return true
}
func (this *DemoResponse_Pong) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DemoResponse_Pong)
	if !ok {
		that2, ok := that.(DemoResponse_Pong)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if !this.Pong.Equal(that1.Pong) {
		return false
	}
	return true
}
func (m *DemoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DemoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DemoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ping != nil {
		{
			size, err := m.Ping.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDemo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintDemo(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DemoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DemoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DemoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Empty != nil {
		{
			size, err := m.Empty.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDemo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Ping != nil {
		{
			size, err := m.Ping.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDemo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Content) > 0 {
		for iNdEx := len(m.Content) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Content[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDemo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Pong != nil {
		{
			size, err := m.Pong.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDemo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DemoResponse_Pong) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DemoResponse_Pong) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DemoResponse_Pong) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pong != nil {
		{
			size, err := m.Pong.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDemo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintDemo(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDemo(dAtA []byte, offset int, v uint64) int {
	offset -= sovDemo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DemoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovDemo(uint64(l))
	}
	if m.Ping != nil {
		l = m.Ping.Size()
		n += 1 + l + sovDemo(uint64(l))
	}
	return n
}

func (m *DemoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pong != nil {
		l = m.Pong.Size()
		n += 1 + l + sovDemo(uint64(l))
	}
	if len(m.Content) > 0 {
		for _, e := range m.Content {
			l = e.Size()
			n += 1 + l + sovDemo(uint64(l))
		}
	}
	if m.Ping != nil {
		l = m.Ping.Size()
		n += 1 + l + sovDemo(uint64(l))
	}
	if m.Empty != nil {
		l = m.Empty.Size()
		n += 1 + l + sovDemo(uint64(l))
	}
	return n
}

func (m *DemoResponse_Pong) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovDemo(uint64(l))
	}
	if m.Pong != nil {
		l = m.Pong.Size()
		n += 1 + l + sovDemo(uint64(l))
	}
	return n
}

func sovDemo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDemo(x uint64) (n int) {
	return sovDemo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DemoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DemoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DemoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ping == nil {
				m.Ping = &api.ExampleRequest{}
			}
			if err := m.Ping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DemoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DemoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DemoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pong", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pong == nil {
				m.Pong = &DemoResponse_Pong{}
			}
			if err := m.Pong.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content, &api.ExampleResponse{})
			if err := m.Content[len(m.Content)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ping == nil {
				m.Ping = &api.ExampleResponse{}
			}
			if err := m.Ping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Empty", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Empty == nil {
				m.Empty = &types.Empty{}
			}
			if err := m.Empty.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DemoResponse_Pong) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pong: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pong: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pong", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pong == nil {
				m.Pong = &api.ExampleResponse{}
			}
			if err := m.Pong.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDemo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDemo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDemo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDemo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDemo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDemo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDemo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDemo = fmt.Errorf("proto: unexpected end of group")
)
